/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JFileChooser;
import java.io.File;
import it.sauronsoftware.jave.AudioAttributes;
import it.sauronsoftware.jave.VideoAttributes;
import it.sauronsoftware.jave.VideoSize;
import it.sauronsoftware.jave.EncodingAttributes;
import it.sauronsoftware.jave.Encoder;
import javax.swing.JOptionPane;
import it.sauronsoftware.jave.EncoderException;

/**
 *
 * @author Mayukh Nair
 */
public class ConvertX extends javax.swing.JFrame {

    /**
     * Creates new form ConvertX
     */
    public ConvertX() {
        initComponents();
    }
     public String fileLocn;
     public String filax;
     public String audiocodec,videocodec,formatid,format;
     public int bitra,chana,sampa,bitrv,framv,size1,size2;
      public File output=new File(filax+formatid);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        filelocation = new javax.swing.JTextField();
        BrowseButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        videopane = new javax.swing.JTabbedPane();
        videopane_holder = new javax.swing.JPanel();
        parampanel = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        audioparam = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        bitr_a = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        chan_a = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        samp_a = new javax.swing.JTextField();
        StartButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        progbar = new javax.swing.JProgressBar();
        AboutButton = new javax.swing.JButton();
        videoparam = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        bitr_v = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        fram_v = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        size_1 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        size_2 = new javax.swing.JTextField();
        preservevideo = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        VideoFormatBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        AudioFormatBox = new javax.swing.JComboBox();
        parampanelaudio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        audioparamaudio = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bitr_a1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        chan_a1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        samp_a1 = new javax.swing.JTextField();
        StartButtonaudio = new javax.swing.JButton();
        ExitButtonAudio = new javax.swing.JButton();
        progbaraudio = new javax.swing.JProgressBar();
        AboutButtonAudio = new javax.swing.JButton();
        preserveaudio = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ConvertX-Video Converter");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose your file"));

        BrowseButton.setText("Browse");
        BrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(filelocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BrowseButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filelocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrowseButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("ConvertX version 0.1 Beta © 2014 Mayukh Nair. All rights reserved.");

        parampanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Geeky Stuff"));
        parampanel.setEnabled(false);

        jLabel59.setText("Unless you know what these parameters mean, you don't need to change them.");

        jLabel60.setText("ConvertX will take care of it.");

        audioparam.setBorder(javax.swing.BorderFactory.createTitledBorder("Audio Parameters"));
        audioparam.setEnabled(false);

        jLabel61.setText("Bitrate:");

        jLabel62.setText("No. of channels:");

        jLabel63.setText("Sampling rate:");

        javax.swing.GroupLayout audioparamLayout = new javax.swing.GroupLayout(audioparam);
        audioparam.setLayout(audioparamLayout);
        audioparamLayout.setHorizontalGroup(
            audioparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(audioparamLayout.createSequentialGroup()
                .addGroup(audioparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(audioparamLayout.createSequentialGroup()
                        .addComponent(jLabel61)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bitr_a, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chan_a, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(audioparamLayout.createSequentialGroup()
                        .addComponent(jLabel63)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(samp_a, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        audioparamLayout.setVerticalGroup(
            audioparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(audioparamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(audioparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(bitr_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62)
                    .addComponent(chan_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(audioparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(samp_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StartButton.setText("Start");
        StartButton.setEnabled(false);
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        progbar.setMaximum(1000);

        AboutButton.setText("About");
        AboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutButtonActionPerformed(evt);
            }
        });

        videoparam.setBorder(javax.swing.BorderFactory.createTitledBorder("Video Parameters"));
        videoparam.setEnabled(false);

        jLabel64.setText("Bitrate:");

        jLabel65.setText("Frame rate:");

        jLabel66.setText("Resolution:");

        jLabel67.setText("x");

        javax.swing.GroupLayout videoparamLayout = new javax.swing.GroupLayout(videoparam);
        videoparam.setLayout(videoparamLayout);
        videoparamLayout.setHorizontalGroup(
            videoparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoparamLayout.createSequentialGroup()
                .addGroup(videoparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(videoparamLayout.createSequentialGroup()
                        .addComponent(jLabel64)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bitr_v, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel65)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fram_v, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addGroup(videoparamLayout.createSequentialGroup()
                        .addComponent(jLabel66)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(size_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel67)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(size_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        videoparamLayout.setVerticalGroup(
            videoparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoparamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(videoparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(bitr_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65)
                    .addComponent(fram_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(videoparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(size_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel67)
                    .addComponent(size_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        preservevideo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        preservevideo.setSelected(true);
        preservevideo.setText("Preserve (Recommended)");
        preservevideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preservevideoActionPerformed(evt);
            }
        });

        jLabel1.setText("This prevents change in video quality");

        javax.swing.GroupLayout parampanelLayout = new javax.swing.GroupLayout(parampanel);
        parampanel.setLayout(parampanelLayout);
        parampanelLayout.setHorizontalGroup(
            parampanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parampanelLayout.createSequentialGroup()
                .addGroup(parampanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(parampanelLayout.createSequentialGroup()
                        .addGroup(parampanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(audioparam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(videoparam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(parampanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addComponent(jLabel59)
                    .addComponent(jLabel60)
                    .addGroup(parampanelLayout.createSequentialGroup()
                        .addComponent(preservevideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(parampanelLayout.createSequentialGroup()
                .addComponent(progbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        parampanelLayout.setVerticalGroup(
            parampanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parampanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel60)
                .addGap(4, 4, 4)
                .addGroup(parampanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preservevideo)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parampanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parampanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(StartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AboutButton))
                    .addGroup(parampanelLayout.createSequentialGroup()
                        .addComponent(audioparam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(videoparam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        VideoFormatBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Flash Video (.flv)", "Audio Video Interleave (.avi)", "MPEG-4 Video (.mp4)", "3GPP Video (.3gp)", "DVD Video (.vob)" }));
        VideoFormatBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideoFormatBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout videopane_holderLayout = new javax.swing.GroupLayout(videopane_holder);
        videopane_holder.setLayout(videopane_holderLayout);
        videopane_holderLayout.setHorizontalGroup(
            videopane_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videopane_holderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(videopane_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(parampanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VideoFormatBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        videopane_holderLayout.setVerticalGroup(
            videopane_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videopane_holderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VideoFormatBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parampanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        videopane.addTab("Convert to Video", videopane_holder);

        AudioFormatBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MPEG-4 Audio Layer 3 (.mp3)", "Wave Audio (.wav)", "OGG Vorbis Audio (.ogg)" }));
        AudioFormatBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AudioFormatBoxActionPerformed(evt);
            }
        });

        parampanelaudio.setBorder(javax.swing.BorderFactory.createTitledBorder("Geeky Stuff"));
        parampanelaudio.setEnabled(false);

        jLabel3.setText("Unless you know what these parameters mean, you don't need to change them.");

        jLabel4.setText("ConvertX will take care of it.");

        audioparamaudio.setBorder(javax.swing.BorderFactory.createTitledBorder("Audio Parameters"));
        audioparamaudio.setEnabled(false);

        jLabel6.setText("Bitrate:");

        jLabel7.setText("No. of channels:");

        jLabel8.setText("Sampling rate:");

        javax.swing.GroupLayout audioparamaudioLayout = new javax.swing.GroupLayout(audioparamaudio);
        audioparamaudio.setLayout(audioparamaudioLayout);
        audioparamaudioLayout.setHorizontalGroup(
            audioparamaudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(audioparamaudioLayout.createSequentialGroup()
                .addGroup(audioparamaudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(audioparamaudioLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bitr_a1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chan_a1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(audioparamaudioLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(samp_a1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        audioparamaudioLayout.setVerticalGroup(
            audioparamaudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(audioparamaudioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(audioparamaudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(audioparamaudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bitr_a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(chan_a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(audioparamaudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(samp_a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        StartButtonaudio.setText("Start");
        StartButtonaudio.setEnabled(false);
        StartButtonaudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonaudioActionPerformed(evt);
            }
        });

        ExitButtonAudio.setText("Exit");
        ExitButtonAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonAudioActionPerformed(evt);
            }
        });

        progbaraudio.setMaximum(1000);

        AboutButtonAudio.setText("About");
        AboutButtonAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutButtonAudioActionPerformed(evt);
            }
        });

        preserveaudio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        preserveaudio.setSelected(true);
        preserveaudio.setText("Preserve (Recommended)");
        preserveaudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preserveaudioActionPerformed(evt);
            }
        });

        jLabel2.setText("This prevents change in audio quality.");

        javax.swing.GroupLayout parampanelaudioLayout = new javax.swing.GroupLayout(parampanelaudio);
        parampanelaudio.setLayout(parampanelaudioLayout);
        parampanelaudioLayout.setHorizontalGroup(
            parampanelaudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parampanelaudioLayout.createSequentialGroup()
                .addComponent(progbaraudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(parampanelaudioLayout.createSequentialGroup()
                .addGroup(parampanelaudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parampanelaudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(parampanelaudioLayout.createSequentialGroup()
                            .addComponent(audioparamaudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(parampanelaudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(StartButtonaudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ExitButtonAudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AboutButtonAudio, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                            .addGap(25, 25, 25))
                        .addComponent(jLabel3))
                    .addComponent(jLabel4)
                    .addGroup(parampanelaudioLayout.createSequentialGroup()
                        .addComponent(preserveaudio)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        parampanelaudioLayout.setVerticalGroup(
            parampanelaudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parampanelaudioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(parampanelaudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preserveaudio)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(parampanelaudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parampanelaudioLayout.createSequentialGroup()
                        .addComponent(StartButtonaudio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExitButtonAudio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AboutButtonAudio))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parampanelaudioLayout.createSequentialGroup()
                        .addComponent(audioparamaudio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progbaraudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(parampanelaudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AudioFormatBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AudioFormatBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parampanelaudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        videopane.addTab("Convert to Audio", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(videopane, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(videopane, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser FilePicker=new JFileChooser();
        int returnVal = FilePicker.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file=FilePicker.getSelectedFile();
        fileLocn=file.getPath();
        filelocation.setText(fileLocn);
        filax=fileLocn.substring(0, fileLocn.indexOf("."));
        }
    }//GEN-LAST:event_BrowseButtonActionPerformed

    private void VideoFormatBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VideoFormatBoxActionPerformed
        // TODO add your handling code here
        parampanel.setEnabled(true);
        StartButton.setEnabled(true);
        int state=VideoFormatBox.getSelectedIndex();
        switch(state){
            case 0:audiocodec="libmp3lame";
            bitra=64000;
            chana=1;
            sampa=22050;
            videocodec="flv";
            bitrv=160000;
            framv=15;
            size1=640;
            size2=480;           
            formatid=".flv";
            format="flv";
            break;
            case 1:audiocodec="libmp3lame";
            bitra=64000;
            chana=1;
            sampa=22050;
            videocodec="libxvid";
            bitrv=192000;
            framv=30;
            size1=640;
            size2=480;
            formatid=".avi";
            format="avi";
            break;
            case 2:audiocodec="libmp3lame";
            bitra=96000;
            chana=1;
            sampa=44100;
            videocodec="mpeg4";
            bitrv=192000;
            framv=30;
            size1=640;
            size2=480;
            formatid=".mp4";
            format="mp4";
            break;
            case 3:audiocodec="libfaac";
            bitra=12000;
            chana=1;
            sampa=8000;
            videocodec="h263";
            bitrv=240000;
            framv=30;
            size1=176;
            size2=144;
            formatid=".3gp";
            format="3gp";
            break;
            case 4:audiocodec="libmp3lame";
            bitra=384000;
            chana=1;
            sampa=48000;
            videocodec="mpeg2video";
            bitrv=4000000;
            framv=30;
            size1=720;
            size2=480;
            formatid=".vob";
            format="vob";
            break;

        }

    }//GEN-LAST:event_VideoFormatBoxActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        // TODO add your handling code here:
        try{
            File input=new File(fileLocn);
            File output=new File(filax+formatid);

            AudioAttributes audio=new AudioAttributes();
            VideoAttributes video=new VideoAttributes();
            audio.setCodec(audiocodec);
            video.setCodec(videocodec);
           if(preservevideo.isSelected()==false){ 
            audio.setBitRate(Integer.parseInt(bitr_a.getText()));
            audio.setChannels(Integer.parseInt(chan_a.getText()));
            audio.setSamplingRate(Integer.parseInt(samp_a.getText()));
            video.setBitRate(Integer.parseInt(bitr_v.getText()));
            video.setFrameRate(Integer.parseInt(fram_v.getText()));
            video.setSize(new VideoSize(Integer.parseInt(size_1.getText()),Integer.parseInt(size_2.getText())));
            EncodingAttributes attrs=new EncodingAttributes();
            attrs.setFormat(format);
            attrs.setAudioAttributes(audio);
            attrs.setVideoAttributes(video);
            Encoder encode=new Encoder();
            encode.encode(input, output, attrs);
            }
           else{
           video.setCodec(VideoAttributes.DIRECT_STREAM_COPY);
           EncodingAttributes attrs=new EncodingAttributes();
            attrs.setFormat(format);
            attrs.setAudioAttributes(audio);
            attrs.setVideoAttributes(video);
            Encoder encode=new Encoder();
            encode.encode(input, output, attrs);
           }
           }
        catch (EncoderException | IllegalArgumentException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_StartButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutButtonActionPerformed
        // TODO add your handling code here:
        Credits.main(null);
    }//GEN-LAST:event_AboutButtonActionPerformed

    private void StartButtonaudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonaudioActionPerformed
        // TODO add your handling code here:
        try{
            File input=new File(fileLocn);
            AudioAttributes audio=new AudioAttributes();
  
          
             if(formatid.equals(".ogg"))
             {
             audio.setCodec(audiocodec);
            EncodingAttributes attrs=new EncodingAttributes();
            attrs.setFormat(format);
            attrs.setAudioAttributes(audio);
            Encoder encode=new Encoder();
            encode.encode(input, output, attrs);
            this.dispose();
            ConvertX.main(null);
           }
               audio.setCodec(audiocodec);
            audio.setBitRate(Integer.parseInt(bitr_a1.getText()));
            audio.setChannels(Integer.parseInt(chan_a1.getText()));
            audio.setSamplingRate(Integer.parseInt(samp_a1.getText()));
            EncodingAttributes attrs=new EncodingAttributes();
            attrs.setFormat(format);
            attrs.setAudioAttributes(audio);
            Encoder encode=new Encoder();
            encode.encode(input, output, attrs);
            
           
        }
        catch (EncoderException | IllegalArgumentException e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
    }//GEN-LAST:event_StartButtonaudioActionPerformed

    private void ExitButtonAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonAudioActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonAudioActionPerformed

    private void AboutButtonAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutButtonAudioActionPerformed
        // TODO add your handling code here:
        Credits.main(null);
    }//GEN-LAST:event_AboutButtonAudioActionPerformed

    private void AudioFormatBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AudioFormatBoxActionPerformed
        // TODO add your handling code here:
        parampanelaudio.setEnabled(true);
        StartButtonaudio.setEnabled(true);
        int state=AudioFormatBox.getSelectedIndex();
        switch(state){
            case 0:audiocodec="libmp3lame";
                   bitra=64000;
                   chana=1;
                   sampa=22050;
                   formatid=".mp3";
                   format="mp3";
                   break;

            case 1:audiocodec="pcm_s16le";
                   bitra=176400;
                   chana=1;
                   sampa=11025;
                   formatid=".wav";
                   format="wav";
                   break;

            case 2:audiocodec="vorbis";
                   bitra=128000;
                   chana=1;
                   sampa=11025;
                   formatid=".ogg";
                   format="ogg";
                   break;

        }
    }//GEN-LAST:event_AudioFormatBoxActionPerformed

    private void preservevideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preservevideoActionPerformed
        if(preservevideo.isSelected()==false)
        {
           audioparam.setEnabled(true);
           videoparam.setEnabled(true);
            bitr_a.setText(""+bitra);
            chan_a.setText(""+chana);
            samp_a.setText(""+sampa);
            bitr_v.setText(""+bitrv);
            fram_v.setText(""+framv);
            size_1.setText(""+size1);
            size_2.setText(""+size2);
        }
        else
        {
           audioparam.setEnabled(false);
           videoparam.setEnabled(false);
            bitr_a.setText("");
            chan_a.setText("");
            samp_a.setText("");
            bitr_v.setText("");
            fram_v.setText("");
            size_1.setText("");
            size_2.setText("");   
        }
    }//GEN-LAST:event_preservevideoActionPerformed

    private void preserveaudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preserveaudioActionPerformed
        // TODO add your handling code here:
        if(preserveaudio.isSelected()==false){
            audioparamaudio.setEnabled(true);
            bitr_a1.setText(""+bitra);
             chan_a1.setText(""+chana);
             samp_a1.setText(""+sampa);
        }
        else{
             audioparamaudio.setEnabled(false);
            bitr_a1.setText("");
             chan_a1.setText("");
             samp_a1.setText("");
        }
    }//GEN-LAST:event_preserveaudioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutButton;
    private javax.swing.JButton AboutButtonAudio;
    private javax.swing.JComboBox AudioFormatBox;
    private javax.swing.JButton BrowseButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ExitButtonAudio;
    private javax.swing.JButton StartButton;
    private javax.swing.JButton StartButtonaudio;
    private javax.swing.JComboBox VideoFormatBox;
    private javax.swing.JPanel audioparam;
    private javax.swing.JPanel audioparamaudio;
    private javax.swing.JTextField bitr_a;
    private javax.swing.JTextField bitr_a1;
    private javax.swing.JTextField bitr_v;
    private javax.swing.JTextField chan_a;
    private javax.swing.JTextField chan_a1;
    private javax.swing.JTextField filelocation;
    private javax.swing.JTextField fram_v;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel parampanel;
    private javax.swing.JPanel parampanelaudio;
    private javax.swing.JCheckBox preserveaudio;
    private javax.swing.JCheckBox preservevideo;
    private javax.swing.JProgressBar progbar;
    private javax.swing.JProgressBar progbaraudio;
    private javax.swing.JTextField samp_a;
    private javax.swing.JTextField samp_a1;
    private javax.swing.JTextField size_1;
    private javax.swing.JTextField size_2;
    private javax.swing.JTabbedPane videopane;
    private javax.swing.JPanel videopane_holder;
    private javax.swing.JPanel videoparam;
    // End of variables declaration//GEN-END:variables
}
