/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JFileChooser;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
//import java.lang.IllegalArgumentException;

import it.sauronsoftware.jave.AudioAttributes;
import it.sauronsoftware.jave.VideoAttributes;
import it.sauronsoftware.jave.VideoSize;
import it.sauronsoftware.jave.EncodingAttributes;
import it.sauronsoftware.jave.Encoder;
import it.sauronsoftware.jave.EncoderException;
//import it.sauronsoftware.jave.InputFormatException;

/**
 *
 * @author Mayukh Nair and Shubham Rao
 */
public class ConvertX extends javax.swing.JFrame {

    /**
     * Creates new form ConvertX
     */
    public ConvertX() {
        initComponents();
    }
     public String fileLocn;
     public String filax;
     public String audiocodec,videocodec,formatid,format;
     public int bitra,chana,sampa,bitrv,framv,size1,size2;
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileSelectionPanel = new javax.swing.JPanel();
        fileLocnTxtField = new javax.swing.JTextField();
        BrowseButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        formatPanel = new javax.swing.JPanel();
        videoFormatComboBox = new javax.swing.JComboBox();
        audioFormatComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        parameterPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        audioParams = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        audioBitrate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        audioChannels = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        samplingRate = new javax.swing.JTextField();
        videoparam = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        videoBitrate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        videoFramerate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        videoResolution1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        videoResolution2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        progbar = new javax.swing.JProgressBar();
        StartButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        AboutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ConvertX-Video Converter");

        fileSelectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose your file"));

        BrowseButton.setText("Browse");
        BrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("File:");

        javax.swing.GroupLayout fileSelectionPanelLayout = new javax.swing.GroupLayout(fileSelectionPanel);
        fileSelectionPanel.setLayout(fileSelectionPanelLayout);
        fileSelectionPanelLayout.setHorizontalGroup(
            fileSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileLocnTxtField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BrowseButton)
                .addContainerGap())
        );
        fileSelectionPanelLayout.setVerticalGroup(
            fileSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(fileLocnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(BrowseButton))
        );

        formatPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Convert to what?"));

        videoFormatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Flash Video (.flv)", "Audio Video Interleave (.avi)", "MPEG-4 Video (.mp4)", "3GPP Video (.3gp)", "DVD Video (.vob)" }));
        videoFormatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoFormatComboBoxActionPerformed(evt);
            }
        });

        audioFormatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MPEG-4 Audio Layer 3 (.mp3)", "Wave Audio (.wav)", "OGG Vorbis Audio (.ogg)" }));
        audioFormatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioFormatComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Video Formats");

        jLabel2.setText("Audio Formats");

        javax.swing.GroupLayout formatPanelLayout = new javax.swing.GroupLayout(formatPanel);
        formatPanel.setLayout(formatPanelLayout);
        formatPanelLayout.setHorizontalGroup(
            formatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(videoFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(audioFormatComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formatPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );
        formatPanelLayout.setVerticalGroup(
            formatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formatPanelLayout.createSequentialGroup()
                .addGroup(formatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formatPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(audioFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formatPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(videoFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        parameterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Geeky Stuff"));
        parameterPanel.setEnabled(false);

        jLabel3.setText("Unless you know what these parameters mean, you don't need to change them.");

        jLabel4.setText("ConvertX will take care of it.");

        audioParams.setBorder(javax.swing.BorderFactory.createTitledBorder("Audio Parameters"));
        audioParams.setEnabled(false);

        jLabel6.setText("Bitrate:");

        jLabel7.setText("No. of channels:");

        jLabel8.setText("Sampling rate:");

        javax.swing.GroupLayout audioParamsLayout = new javax.swing.GroupLayout(audioParams);
        audioParams.setLayout(audioParamsLayout);
        audioParamsLayout.setHorizontalGroup(
            audioParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(audioParamsLayout.createSequentialGroup()
                .addGroup(audioParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(audioParamsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(audioBitrate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(audioChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(audioParamsLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(samplingRate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        audioParamsLayout.setVerticalGroup(
            audioParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(audioParamsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(audioParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(audioBitrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(audioChannels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(audioParamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(samplingRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        videoparam.setBorder(javax.swing.BorderFactory.createTitledBorder("Video Parameters"));
        videoparam.setEnabled(false);

        jLabel9.setText("Bitrate:");

        jLabel10.setText("Frame rate:");

        jLabel11.setText("Resolution:");

        jLabel12.setText("x");

        javax.swing.GroupLayout videoparamLayout = new javax.swing.GroupLayout(videoparam);
        videoparam.setLayout(videoparamLayout);
        videoparamLayout.setHorizontalGroup(
            videoparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoparamLayout.createSequentialGroup()
                .addGroup(videoparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(videoparamLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(videoBitrate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(videoFramerate, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                    .addGroup(videoparamLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(videoResolution1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(videoResolution2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        videoparamLayout.setVerticalGroup(
            videoparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoparamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(videoparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(videoBitrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(videoFramerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(videoparamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(videoResolution1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(videoResolution2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout parameterPanelLayout = new javax.swing.GroupLayout(parameterPanel);
        parameterPanel.setLayout(parameterPanelLayout);
        parameterPanelLayout.setHorizontalGroup(
            parameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parameterPanelLayout.createSequentialGroup()
                .addGroup(parameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parameterPanelLayout.createSequentialGroup()
                        .addComponent(audioParams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(videoparam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        parameterPanelLayout.setVerticalGroup(
            parameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parameterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parameterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(audioParams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(videoparam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel13.setText("ConvertX version 0.2 Alpha (Video-only) © 2014 Mayukh Nair. All rights reserved.");

        progbar.setMaximum(1000);

        StartButton.setText("Start");
        StartButton.setEnabled(false);
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        AboutButton.setText("About");
        AboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formatPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parameterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progbar, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parameterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartButton)
                    .addComponent(ExitButton)
                    .addComponent(AboutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseButtonActionPerformed
        // TODO add your handling code here:
        audioFormatComboBox.setEnabled(true);
        JFileChooser FilePicker=new JFileChooser();
        int returnVal = FilePicker.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file=FilePicker.getSelectedFile();
        formatPanel.setEnabled(true);
        fileLocn=file.getPath();
        fileLocnTxtField.setText(fileLocn);
        filax=fileLocn.substring(0, fileLocn.indexOf("."));
        }
    }//GEN-LAST:event_BrowseButtonActionPerformed

    private void videoFormatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoFormatComboBoxActionPerformed
        // TODO add your handling code here:
        audioFormatComboBox.setEnabled(false);
        parameterPanel.setEnabled(true);
        audioParams.setEnabled(true);
        videoparam.setEnabled(true);
        StartButton.setEnabled(true);
        int state=videoFormatComboBox.getSelectedIndex();
        switch(state){
            case 0:audiocodec="libmp3lame";
                   bitra=64000;
                   chana=1;
                   sampa=22050;
                   videocodec="flv";
                   bitrv=160000;
                   framv=15;
                   size1=640;
                   size2=480;
                   audioBitrate.setText(""+bitra);
                   audioChannels.setText(""+chana);
                   samplingRate.setText(""+sampa);
                   videoBitrate.setText(""+bitrv);
                   videoFramerate.setText(""+framv);
                   videoResolution1.setText(""+size1);
                   videoResolution2.setText(""+size2);
                   formatid=".flv";
                   format="flv";
                   break;
           case 1:audiocodec="libmp3lame";
                   bitra=64000;
                   chana=1;
                   sampa=22050;
                   videocodec="libxvid";
                   bitrv=192000;
                   framv=30;
                   size1=640;
                   size2=480;
                   audioBitrate.setText(""+bitra);
                   audioChannels.setText(""+chana);
                   samplingRate.setText(""+sampa);
                   videoBitrate.setText(""+bitrv);
                   videoFramerate.setText(""+framv);
                   videoResolution1.setText(""+size1);
                   videoResolution2.setText(""+size2);
                   formatid=".avi";
                   format="avi";
                   break;
           case 2:audiocodec="libmp3lame";
                   bitra=96000;
                   chana=1;
                   sampa=44100;
                   videocodec="mpeg4";
                   bitrv=192000;
                   framv=30;
                   size1=640;
                   size2=480;
                   audioBitrate.setText(""+bitra);
                   audioChannels.setText(""+chana);
                   samplingRate.setText(""+sampa);
                   videoBitrate.setText(""+bitrv);
                   videoFramerate.setText(""+framv);
                   videoResolution1.setText(""+size1);
                   videoResolution2.setText(""+size2);
                   formatid=".avi";
                   format="avi";
                   break;
        case 3:audiocodec="libfaac";
                   bitra=12000;
                   chana=1;
                   sampa=8000;
                   videocodec="h263";
                   bitrv=240000;
                   framv=30;
                   size1=176;
                   size2=144;
                   audioBitrate.setText(""+bitra);
                   audioChannels.setText(""+chana);
                   samplingRate.setText(""+sampa);
                   videoBitrate.setText(""+bitrv);
                   videoFramerate.setText(""+framv);
                   videoResolution1.setText(""+size1);
                   videoResolution2.setText(""+size2);
                   formatid=".3gp";
                   format="3gp";
                   break;
        case 4:audiocodec="libmp3lame";
                   bitra=384000;
                   chana=1;
                   sampa=48000;
                   videocodec="mpeg2video";
                   bitrv=4000000;
                   framv=30;
                   size1=720;
                   size2=480;
                   audioBitrate.setText(""+bitra);
                   audioChannels.setText(""+chana);
                   samplingRate.setText(""+sampa);
                   videoBitrate.setText(""+bitrv);
                   videoFramerate.setText(""+framv);
                   videoResolution1.setText(""+size1);
                   videoResolution2.setText(""+size2);
                   formatid=".vob";
                   format="vob";
                   break;
                  
        }
         
    }//GEN-LAST:event_videoFormatComboBoxActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        // TODO add your handling code here:
        try{
        File input=new File(fileLocn);
        File output=new File(filax+formatid); 
        AudioAttributes audio=new AudioAttributes();
        audio.setCodec(audiocodec);
        audio.setBitRate(Integer.parseInt(audioBitrate.getText()));
        audio.setChannels(Integer.parseInt(audioChannels.getText()));
        audio.setSamplingRate(Integer.parseInt(samplingRate.getText()));
         VideoAttributes video=new VideoAttributes();
        video.setCodec(videocodec);
        video.setBitRate(Integer.parseInt(videoBitrate.getText()));
        video.setFrameRate(Integer.parseInt(videoFramerate.getText()));
        video.setSize(new VideoSize(Integer.parseInt(videoResolution1.getText()),Integer.parseInt(videoResolution2.getText())));
        EncodingAttributes attrs=new EncodingAttributes();
        attrs.setFormat(format);
        attrs.setAudioAttributes(audio);
        attrs.setVideoAttributes(video);
        Encoder encode=new Encoder();
        encode.encode(input, output, attrs);
        }
  
       catch (EncoderException | IllegalArgumentException e){
           JOptionPane.showMessageDialog(null,
                   "Sorry, We encountered an error. Please check that everything is ok\n"+
                   "If you are in mood to investigate, here is the stack trace:\n"
                    + e.getStackTrace(),"Error",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_StartButtonActionPerformed

    private void AboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutButtonActionPerformed
        // TODO add your handling code here:
        Credits.main(null);
    }//GEN-LAST:event_AboutButtonActionPerformed

    private void audioFormatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioFormatComboBoxActionPerformed
        // TODO add your handling code here:
        videoFormatComboBox.setEnabled(false);
        parameterPanel.setEnabled(true);
        audioParams.setEnabled(true);
        videoparam.setEnabled(false);
        StartButton.setEnabled(true);
        int state=audioFormatComboBox.getSelectedIndex();
        switch(state){
            case 0:audiocodec="libmp3lame";
                   bitra=64000;
                   chana=1;
                   sampa=22050;
                   audioBitrate.setText(""+bitra);
                   audioChannels.setText(""+chana);
                   samplingRate.setText(""+sampa);
                   formatid=".mp3";
                   format="mp3";
                   break;
            case 1:audiocodec="pcm_s16le";
                   bitra=176400;
                   chana=1;
                   sampa=11025;
                   audioBitrate.setText(""+bitra);
                   audioChannels.setText(""+chana);
                   samplingRate.setText(""+sampa);
                   formatid=".wav";
                   format="wav";
                   break;

            case 2:audiocodec="vorbis";
                   bitra=128000;
                   chana=1;
                   sampa=11025;
                   audioBitrate.setText(""+bitra);
                   audioChannels.setText(""+chana);
                   samplingRate.setText(""+sampa);
                   formatid=".ogg";
                   format="ogg";
                   break;
        }
    }//GEN-LAST:event_audioFormatComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            javax.swing.UIManager.setLookAndFeel(
                    javax.swing.UIManager.getSystemLookAndFeelClassName());
        } 
        catch (ClassNotFoundException | InstantiationException | 
                IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Credits.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ConvertX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ConvertX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ConvertX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ConvertX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutButton;
    private javax.swing.JButton BrowseButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JTextField audioBitrate;
    private javax.swing.JTextField audioChannels;
    private javax.swing.JComboBox audioFormatComboBox;
    private javax.swing.JPanel audioParams;
    private javax.swing.JTextField fileLocnTxtField;
    private javax.swing.JPanel fileSelectionPanel;
    private javax.swing.JPanel formatPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel parameterPanel;
    private javax.swing.JProgressBar progbar;
    private javax.swing.JTextField samplingRate;
    private javax.swing.JTextField videoBitrate;
    private javax.swing.JComboBox videoFormatComboBox;
    private javax.swing.JTextField videoFramerate;
    private javax.swing.JTextField videoResolution1;
    private javax.swing.JTextField videoResolution2;
    private javax.swing.JPanel videoparam;
    // End of variables declaration//GEN-END:variables
}
